### ISSUE TITLE
Any idea if this works with Azure DevOps Pipelines? [question]

### ISSUE THREAD

**Issue by cocowalla** [devjoes/DockerComposeFixture#10]
This looks really useful for local development, but I'm wondering if it will work with cloud-hosted CI solutions, most specifically Azure DevOps Pipelines?

**Comment by devjoes** [comment]
I use it with Azure DevOps on private build agents. I see no reason why it wouldn't work on the cloud hosted one's though. Let me know if you have any issues.

**Comment by wiruzman** [comment]
I tried to use it on Hosted build agent on Azure DevOps, but it just hangs in the test step.
