### ISSUE TITLE
Update to v2

### ISSUE THREAD

**Issue by lachywoolies** [devjoes/DockerComposeFixture#18]
Docker compose v1 and the syntax `docker-compose` is no longer updated and also no longer available in new releases of Docker Desktop. It's been replaced with the v2 syntax `docker compose`  - https://docs.docker.com/compose/migrate/

Is it possible to update this package to support/use the newer v2 syntax?

We're no longer able to use DockerComposeFixture when running on the latest microsoft azure dev ops build agents, their latest build agents only support the v2 syntax.

**Comment by christophergunn** [comment]
@lachywoolies this should be addressed in the latest v1.2.0 release.
